// Decompiled with JetBrains decompiler
// Type: Intermech.CADInterface.Proxies.Cadmech.IMTextEntityId
// Assembly: Intermech.Tools.Components, Version=7.0.2.1112, Culture=neutral, PublicKeyToken=null
// MVID: B3B1E810-E6FF-4FCB-865A-C312BFC44AFF
// Assembly location: D:\IPS\Client\Intermech.Tools.Components.dll
// XML documentation location: D:\IPS\Client\Intermech.Tools.Components.xml

#nullable disable
namespace Intermech.CADInterface.Proxies.Cadmech;

/// <summary>
/// 
/// </summary>
public enum IMTextEntityId
{
  Entity2d,
  Entity3d,
  PointEnt2d,
  PointEnt3d,
  Position2d,
  Position3d,
  PointOnCurve2d,
  PointOnCurve3d,
  PointOnSurface,
  BoundedPlane,
  CircArc2d,
  CircArc3d,
  Conic2d,
  Conic3d,
  Curve2d,
  Curve3d,
  EllipArc2d,
  EllipArc3d,
  Line2d,
  Line3d,
  LinearEnt2d,
  LinearEnt3d,
  LineSeg2d,
  LineSeg3d,
  PlanarEnt,
  Plane,
  Ray2d,
  Ray3d,
  Surface,
  Sphere,
  Cylinder,
  Torus,
  Cone,
  SplineEnt2d,
  Polyline2d,
  AugPolyline2d,
  NurbCurve2d,
  DSpline2d,
  CubicSplineCurve2d,
  SplineEnt3d,
  Polyline3d,
  AugPolyline3d,
  NurbCurve3d,
  DSpline3d,
  CubicSplineCurve3d,
  TrimmedCrv2d,
  CompositeCrv2d,
  CompositeCrv3d,
  ExternalSurface,
  NurbSurface,
  TrimmedSurface,
  OffsetSurface,
  Envelope2d,
  CurveBoundedSurface,
  ExternalCurve3d,
  ExternalCurve2d,
  SurfaceCurve2dTo3d,
  SurfaceCurve3dTo2d,
  ExternalBoundedSurface,
  CurveCurveInt2d,
  CurveCurveInt3d,
  BoundBlock2d,
  BoundBlock3d,
  OffsetCurve2d,
  OffsetCurve3d,
  PolynomCurve3d,
  BezierCurve3d,
  Object,
  FitData3d,
  Hatch,
  TrimmedCurve2d,
  TrimmedCurve3d,
  CurveSampleData,
  EllipCone,
  EllipCylinder,
  IntervalBoundBlock,
  ClipBoundary2d,
  ExternalObject,
  CurveSurfaceInt,
  SurfaceSurfaceInt,
}
