// Decompiled with JetBrains decompiler
// Type: Interop.Cadmech.IM_EntityId
// Assembly: Interop.IMText, Version=1.0.0.0, Culture=neutral, PublicKeyToken=8d2bc20ab69e4bb4
// MVID: 429E38D4-3785-4B44-8CD1-02E4A9CDD7BF
// Assembly location: D:\IPS\Client\Interop.IMText.dll

#nullable disable
namespace Interop.Cadmech;

public enum IM_EntityId
{
  IM_kEntity2d,
  IM_kEntity3d,
  IM_kPointEnt2d,
  IM_kPointEnt3d,
  IM_kPosition2d,
  IM_kPosition3d,
  IM_kPointOnCurve2d,
  IM_kPointOnCurve3d,
  IM_kPointOnSurface,
  IM_kBoundedPlane,
  IM_kCircArc2d,
  IM_kCircArc3d,
  IM_kConic2d,
  IM_kConic3d,
  IM_kCurve2d,
  IM_kCurve3d,
  IM_kEllipArc2d,
  IM_kEllipArc3d,
  IM_kLine2d,
  IM_kLine3d,
  IM_kLinearEnt2d,
  IM_kLinearEnt3d,
  IM_kLineSeg2d,
  IM_kLineSeg3d,
  IM_kPlanarEnt,
  IM_kPlane,
  IM_kRay2d,
  IM_kRay3d,
  IM_kSurface,
  IM_kSphere,
  IM_kCylinder,
  IM_kTorus,
  IM_kCone,
  IM_kSplineEnt2d,
  IM_kPolyline2d,
  IM_kAugPolyline2d,
  IM_kNurbCurve2d,
  IM_kDSpline2d,
  IM_kCubicSplineCurve2d,
  IM_kSplineEnt3d,
  IM_kPolyline3d,
  IM_kAugPolyline3d,
  IM_kNurbCurve3d,
  IM_kDSpline3d,
  IM_kCubicSplineCurve3d,
  IM_kTrimmedCrv2d,
  IM_kCompositeCrv2d,
  IM_kCompositeCrv3d,
  IM_kExternalSurface,
  IM_kNurbSurface,
  IM_kTrimmedSurface,
  IM_kOffsetSurface,
  IM_kEnvelope2d,
  IM_kCurveBoundedSurface,
  IM_kExternalCurve3d,
  IM_kExternalCurve2d,
  IM_kSurfaceCurve2dTo3d,
  IM_kSurfaceCurve3dTo2d,
  IM_kExternalBoundedSurface,
  IM_kCurveCurveInt2d,
  IM_kCurveCurveInt3d,
  IM_kBoundBlock2d,
  IM_kBoundBlock3d,
  IM_kOffsetCurve2d,
  IM_kOffsetCurve3d,
  IM_kPolynomCurve3d,
  IM_kBezierCurve3d,
  IM_kObject,
  IM_kFitData3d,
  IM_kHatch,
  IM_kTrimmedCurve2d,
  IM_kTrimmedCurve3d,
  IM_kCurveSampleData,
  IM_kEllipCone,
  IM_kEllipCylinder,
  IM_kIntervalBoundBlock,
  IM_kClipBoundary2d,
  IM_kExternalObject,
  IM_kCurveSurfaceInt,
  IM_kSurfaceSurfaceInt,
}
