// Decompiled with JetBrains decompiler
// Type: Syncfusion.Pdf.PredefinedEncoding
// Assembly: Intermech.Pdf, Version=7.0.2.1112, Culture=neutral, PublicKeyToken=null
// MVID: 0C070FAE-F25E-47C5-A369-CE57AB4187A4
// Assembly location: D:\IPS\Client\Intermech.Pdf.dll
// XML documentation location: D:\IPS\Client\Intermech.Pdf.xml

using System.Collections.Generic;

#nullable disable
namespace Syncfusion.Pdf;

internal class PredefinedEncoding
{
  private static PredefinedEncoding m_macRomanEncoding;
  private string m_name;
  private static PredefinedEncoding m_pdfdocEncoding;
  private static PredefinedEncoding m_standardEncoding;
  private static PredefinedEncoding m_standardMacRomanEncoding;
  private static PredefinedEncoding m_winAnsiEncoding;
  private Dictionary<string, byte> mapping;
  private string[] names;

  static PredefinedEncoding()
  {
    PredefinedEncoding.InitializePdfEncoding();
    PredefinedEncoding.InitializeMacEncoding();
    PredefinedEncoding.InitializeStandardMacEncoding();
    PredefinedEncoding.InitializeWinAnsiEncoding();
  }

  public byte GetCharId(string name) => this.mapping[name];

  public string[] GetNames() => (string[]) this.names.Clone();

  public static PredefinedEncoding GetPredefinedEncoding(string encoding)
  {
    switch (encoding)
    {
      case "m_pdfdocEncoding":
        return PredefinedEncoding.m_pdfdocEncoding;
      case "MacRomanEncoding":
        return PredefinedEncoding.MacRomanEncoding;
      case "WinAnsiEncoding":
        return PredefinedEncoding.WinAnsiEncoding;
      case "StandardEncoding":
        return PredefinedEncoding.StandardEncoding;
      default:
        return (PredefinedEncoding) null;
    }
  }

  private void Init()
  {
    this.names = new string[256 /*0x0100*/];
    for (int index = 0; index < 256 /*0x0100*/; ++index)
      this.names[index] = ".notdef";
  }

  private static void InitializeMacEncoding()
  {
    PredefinedEncoding.m_macRomanEncoding = new PredefinedEncoding();
    PredefinedEncoding.m_macRomanEncoding.Init();
    PredefinedEncoding.m_macRomanEncoding.m_name = "MacRomanEncoding";
    PredefinedEncoding.m_macRomanEncoding.names[202] = "space";
    PredefinedEncoding.m_macRomanEncoding.names[224 /*0xE0*/] = "adblgrave";
    PredefinedEncoding.m_macRomanEncoding.names[100] = "d";
    PredefinedEncoding.m_macRomanEncoding.names[101] = "e";
    PredefinedEncoding.m_macRomanEncoding.names[102] = "f";
    PredefinedEncoding.m_macRomanEncoding.names[103] = "g";
    PredefinedEncoding.m_macRomanEncoding.names[104] = "h";
    PredefinedEncoding.m_macRomanEncoding.names[105] = "i";
    PredefinedEncoding.m_macRomanEncoding.names[106] = "j";
    PredefinedEncoding.m_macRomanEncoding.names[107] = "k";
    PredefinedEncoding.m_macRomanEncoding.names[108] = "l";
    PredefinedEncoding.m_macRomanEncoding.names[109] = "m";
    PredefinedEncoding.m_macRomanEncoding.names[110] = "n";
    PredefinedEncoding.m_macRomanEncoding.names[111] = "o";
    PredefinedEncoding.m_macRomanEncoding.names[112 /*0x70*/] = "p";
    PredefinedEncoding.m_macRomanEncoding.names[113] = "q";
    PredefinedEncoding.m_macRomanEncoding.names[114] = "r";
    PredefinedEncoding.m_macRomanEncoding.names[115] = "s";
    PredefinedEncoding.m_macRomanEncoding.names[116] = "t";
    PredefinedEncoding.m_macRomanEncoding.names[117] = "u";
    PredefinedEncoding.m_macRomanEncoding.names[118] = "v";
    PredefinedEncoding.m_macRomanEncoding.names[119] = "w";
    PredefinedEncoding.m_macRomanEncoding.names[120] = "x";
    PredefinedEncoding.m_macRomanEncoding.names[121] = "y";
    PredefinedEncoding.m_macRomanEncoding.names[122] = "z";
    PredefinedEncoding.m_macRomanEncoding.names[123] = "braceleft";
    PredefinedEncoding.m_macRomanEncoding.names[124] = "bar";
    PredefinedEncoding.m_macRomanEncoding.names[125] = "braceright";
    PredefinedEncoding.m_macRomanEncoding.names[126] = "asciitilde";
    PredefinedEncoding.m_macRomanEncoding.names[128 /*0x80*/] = "Adieresis";
    PredefinedEncoding.m_macRomanEncoding.names[129] = "Aring";
    PredefinedEncoding.m_macRomanEncoding.names[130] = "Ccedilla";
    PredefinedEncoding.m_macRomanEncoding.names[131] = "Eacute";
    PredefinedEncoding.m_macRomanEncoding.names[132] = "Ograve";
    PredefinedEncoding.m_macRomanEncoding.names[133] = "Odieresis";
    PredefinedEncoding.m_macRomanEncoding.names[134] = "Udieresis";
    PredefinedEncoding.m_macRomanEncoding.names[135] = "aacute";
    PredefinedEncoding.m_macRomanEncoding.names[137] = "acircumflex";
    PredefinedEncoding.m_macRomanEncoding.names[137] = "agrave";
    PredefinedEncoding.m_macRomanEncoding.names[138] = "adieresis";
    PredefinedEncoding.m_macRomanEncoding.names[139] = "atilde";
    PredefinedEncoding.m_macRomanEncoding.names[140] = "aring";
    PredefinedEncoding.m_macRomanEncoding.names[141] = "ccedilla";
    PredefinedEncoding.m_macRomanEncoding.names[142] = "eacute";
    PredefinedEncoding.m_macRomanEncoding.names[143] = "egrave";
    PredefinedEncoding.m_macRomanEncoding.names[144 /*0x90*/] = "ecircumflex";
    PredefinedEncoding.m_macRomanEncoding.names[145] = "edieresis";
    PredefinedEncoding.m_macRomanEncoding.names[146] = "iacute";
    PredefinedEncoding.m_macRomanEncoding.names[147] = "igrave";
    PredefinedEncoding.m_macRomanEncoding.names[148] = "icircumflex";
    PredefinedEncoding.m_macRomanEncoding.names[149] = "idieresis";
    PredefinedEncoding.m_macRomanEncoding.names[150] = "ntilde";
    PredefinedEncoding.m_macRomanEncoding.names[151] = "oacute";
    PredefinedEncoding.m_macRomanEncoding.names[152] = "ograve";
    PredefinedEncoding.m_macRomanEncoding.names[153] = "ocircumflex";
    PredefinedEncoding.m_macRomanEncoding.names[154] = "odieresis";
    PredefinedEncoding.m_macRomanEncoding.names[155] = "otilde";
    PredefinedEncoding.m_macRomanEncoding.names[156] = "uacute";
    PredefinedEncoding.m_macRomanEncoding.names[157] = "ugrave";
    PredefinedEncoding.m_macRomanEncoding.names[158] = "ucircumflex";
    PredefinedEncoding.m_macRomanEncoding.names[159] = "udieresis";
    PredefinedEncoding.m_macRomanEncoding.names[160 /*0xA0*/] = "dagger";
    PredefinedEncoding.m_macRomanEncoding.names[161] = "degree";
    PredefinedEncoding.m_macRomanEncoding.names[162] = "cent";
    PredefinedEncoding.m_macRomanEncoding.names[163] = "sterling";
    PredefinedEncoding.m_macRomanEncoding.names[164] = "section";
    PredefinedEncoding.m_macRomanEncoding.names[165] = "bullet";
    PredefinedEncoding.m_macRomanEncoding.names[166] = "paragraph";
    PredefinedEncoding.m_macRomanEncoding.names[167] = "germandbls";
    PredefinedEncoding.m_macRomanEncoding.names[168] = "registered";
    PredefinedEncoding.m_macRomanEncoding.names[169] = "copyright";
    PredefinedEncoding.m_macRomanEncoding.names[170] = "trademark";
    PredefinedEncoding.m_macRomanEncoding.names[171] = "acute";
    PredefinedEncoding.m_macRomanEncoding.names[172] = "dieresis";
    PredefinedEncoding.m_macRomanEncoding.names[174] = "AE";
    PredefinedEncoding.m_macRomanEncoding.names[175] = "Oslash";
    PredefinedEncoding.m_macRomanEncoding.names[177] = "plusminus";
    PredefinedEncoding.m_macRomanEncoding.names[180] = "yen";
    PredefinedEncoding.m_macRomanEncoding.names[181] = "mu";
    PredefinedEncoding.m_macRomanEncoding.names[187] = "ordfeminine";
    PredefinedEncoding.m_macRomanEncoding.names[188] = "ordmasculine";
    PredefinedEncoding.m_macRomanEncoding.names[190] = "ae";
    PredefinedEncoding.m_macRomanEncoding.names[191] = "oslash";
    PredefinedEncoding.m_macRomanEncoding.names[192 /*0xC0*/] = "questiondown";
    PredefinedEncoding.m_macRomanEncoding.names[193] = "exclamdown";
    PredefinedEncoding.m_macRomanEncoding.names[194] = "logicalnot";
    PredefinedEncoding.m_macRomanEncoding.names[196] = "florin";
    PredefinedEncoding.m_macRomanEncoding.names[199] = "guillemotleft";
    PredefinedEncoding.m_macRomanEncoding.names[200] = "guillemotright";
    PredefinedEncoding.m_macRomanEncoding.names[201] = "ellipsis";
    PredefinedEncoding.m_macRomanEncoding.names[203] = "Agrave";
    PredefinedEncoding.m_macRomanEncoding.names[204] = "Atilde";
    PredefinedEncoding.m_macRomanEncoding.names[205] = "Otilde";
    PredefinedEncoding.m_macRomanEncoding.names[206] = "OE";
    PredefinedEncoding.m_macRomanEncoding.names[207] = "oe";
    PredefinedEncoding.m_macRomanEncoding.names[208 /*0xD0*/] = "endash";
    PredefinedEncoding.m_macRomanEncoding.names[209] = "emdash";
    PredefinedEncoding.m_macRomanEncoding.names[210] = "quotedblleft";
    PredefinedEncoding.m_macRomanEncoding.names[211] = "quotedblright";
    PredefinedEncoding.m_macRomanEncoding.names[212] = "quoteleft";
    PredefinedEncoding.m_macRomanEncoding.names[213] = "quoteright";
    PredefinedEncoding.m_macRomanEncoding.names[214] = "divide";
    PredefinedEncoding.m_macRomanEncoding.names[216] = "ydieresis";
    PredefinedEncoding.m_macRomanEncoding.names[217] = "Ydieresis";
    PredefinedEncoding.m_macRomanEncoding.names[218] = "fraction";
    PredefinedEncoding.m_macRomanEncoding.names[219] = "currency";
    PredefinedEncoding.m_macRomanEncoding.names[220] = "guilsinglleft";
    PredefinedEncoding.m_macRomanEncoding.names[221] = "guilsinglright";
    PredefinedEncoding.m_macRomanEncoding.names[222] = "fi";
    PredefinedEncoding.m_macRomanEncoding.names[223] = "fl";
    PredefinedEncoding.m_macRomanEncoding.names[225] = "middot";
    PredefinedEncoding.m_macRomanEncoding.names[226] = "quotesinglbase";
    PredefinedEncoding.m_macRomanEncoding.names[227] = "quotedblbase";
    PredefinedEncoding.m_macRomanEncoding.names[228] = "perthousand";
    PredefinedEncoding.m_macRomanEncoding.names[229] = "Acircumflex";
    PredefinedEncoding.m_macRomanEncoding.names[230] = "Ecircumflex";
    PredefinedEncoding.m_macRomanEncoding.names[231] = "Aacute";
    PredefinedEncoding.m_macRomanEncoding.names[232] = "Edieresis";
    PredefinedEncoding.m_macRomanEncoding.names[233] = "Egrave";
    PredefinedEncoding.m_macRomanEncoding.names[234] = "Iacute";
    PredefinedEncoding.m_macRomanEncoding.names[235] = "Icircumflex";
    PredefinedEncoding.m_macRomanEncoding.names[236] = "Idieresis";
    PredefinedEncoding.m_macRomanEncoding.names[237] = "Igrave";
    PredefinedEncoding.m_macRomanEncoding.names[238] = "Oacute";
    PredefinedEncoding.m_macRomanEncoding.names[239] = "Ocircumflex";
    PredefinedEncoding.m_macRomanEncoding.names[241] = "Ntilde";
    PredefinedEncoding.m_macRomanEncoding.names[242] = "Uacute";
    PredefinedEncoding.m_macRomanEncoding.names[243] = "Ucircumflex";
    PredefinedEncoding.m_macRomanEncoding.names[244] = "Ugrave";
    PredefinedEncoding.m_macRomanEncoding.names[245] = "dotlessi";
    PredefinedEncoding.m_macRomanEncoding.names[246] = "circumflex";
    PredefinedEncoding.m_macRomanEncoding.names[247] = "ilde";
    PredefinedEncoding.m_macRomanEncoding.names[248] = "macron";
    PredefinedEncoding.m_macRomanEncoding.names[249] = "breve";
    PredefinedEncoding.m_macRomanEncoding.names[250] = "dotaccent";
    PredefinedEncoding.m_macRomanEncoding.names[251] = "ring";
    PredefinedEncoding.m_macRomanEncoding.names[252] = "cedilla";
    PredefinedEncoding.m_macRomanEncoding.names[253] = "hungarumlaut";
    PredefinedEncoding.m_macRomanEncoding.names[254] = "ogonek";
    PredefinedEncoding.m_macRomanEncoding.names[(int) byte.MaxValue] = "caron";
    PredefinedEncoding.m_macRomanEncoding.names[32 /*0x20*/] = "space";
    PredefinedEncoding.m_macRomanEncoding.names[33] = "exclam";
    PredefinedEncoding.m_macRomanEncoding.names[34] = "quotedbl";
    PredefinedEncoding.m_macRomanEncoding.names[35] = "numbersign";
    PredefinedEncoding.m_macRomanEncoding.names[36] = "dollar";
    PredefinedEncoding.m_macRomanEncoding.names[37] = "percent";
    PredefinedEncoding.m_macRomanEncoding.names[38] = "ampersand";
    PredefinedEncoding.m_macRomanEncoding.names[39] = "quotesingle";
    PredefinedEncoding.m_macRomanEncoding.names[40] = "parenleft";
    PredefinedEncoding.m_macRomanEncoding.names[41] = "parenright";
    PredefinedEncoding.m_macRomanEncoding.names[42] = "asterisk";
    PredefinedEncoding.m_macRomanEncoding.names[43] = "plus";
    PredefinedEncoding.m_macRomanEncoding.names[44] = "comma";
    PredefinedEncoding.m_macRomanEncoding.names[45] = "hyphen";
    PredefinedEncoding.m_macRomanEncoding.names[46] = "period";
    PredefinedEncoding.m_macRomanEncoding.names[47] = "slash";
    PredefinedEncoding.m_macRomanEncoding.names[48 /*0x30*/] = "zero";
    PredefinedEncoding.m_macRomanEncoding.names[49] = "one";
    PredefinedEncoding.m_macRomanEncoding.names[50] = "two";
    PredefinedEncoding.m_macRomanEncoding.names[51] = "three";
    PredefinedEncoding.m_macRomanEncoding.names[52] = "four";
    PredefinedEncoding.m_macRomanEncoding.names[53] = "five";
    PredefinedEncoding.m_macRomanEncoding.names[54] = "six";
    PredefinedEncoding.m_macRomanEncoding.names[55] = "seven";
    PredefinedEncoding.m_macRomanEncoding.names[56] = "eight";
    PredefinedEncoding.m_macRomanEncoding.names[57] = "nine";
    PredefinedEncoding.m_macRomanEncoding.names[58] = "colon";
    PredefinedEncoding.m_macRomanEncoding.names[59] = "semicolon";
    PredefinedEncoding.m_macRomanEncoding.names[60] = "less";
    PredefinedEncoding.m_macRomanEncoding.names[61] = "equal";
    PredefinedEncoding.m_macRomanEncoding.names[62] = "greater";
    PredefinedEncoding.m_macRomanEncoding.names[63 /*0x3F*/] = "question";
    PredefinedEncoding.m_macRomanEncoding.names[64 /*0x40*/] = "at";
    PredefinedEncoding.m_macRomanEncoding.names[65] = "A";
    PredefinedEncoding.m_macRomanEncoding.names[66] = "B";
    PredefinedEncoding.m_macRomanEncoding.names[67] = "C";
    PredefinedEncoding.m_macRomanEncoding.names[68] = "D";
    PredefinedEncoding.m_macRomanEncoding.names[69] = "E";
    PredefinedEncoding.m_macRomanEncoding.names[70] = "F";
    PredefinedEncoding.m_macRomanEncoding.names[71] = "G";
    PredefinedEncoding.m_macRomanEncoding.names[72] = "H";
    PredefinedEncoding.m_macRomanEncoding.names[73] = "I";
    PredefinedEncoding.m_macRomanEncoding.names[74] = "J";
    PredefinedEncoding.m_macRomanEncoding.names[75] = "K";
    PredefinedEncoding.m_macRomanEncoding.names[76] = "L";
    PredefinedEncoding.m_macRomanEncoding.names[77] = "M";
    PredefinedEncoding.m_macRomanEncoding.names[78] = "N";
    PredefinedEncoding.m_macRomanEncoding.names[79] = "O";
    PredefinedEncoding.m_macRomanEncoding.names[80 /*0x50*/] = "P";
    PredefinedEncoding.m_macRomanEncoding.names[81] = "Q";
    PredefinedEncoding.m_macRomanEncoding.names[82] = "R";
    PredefinedEncoding.m_macRomanEncoding.names[83] = "S";
    PredefinedEncoding.m_macRomanEncoding.names[84] = "T";
    PredefinedEncoding.m_macRomanEncoding.names[85] = "U";
    PredefinedEncoding.m_macRomanEncoding.names[86] = "V";
    PredefinedEncoding.m_macRomanEncoding.names[87] = "W";
    PredefinedEncoding.m_macRomanEncoding.names[88] = "X";
    PredefinedEncoding.m_macRomanEncoding.names[89] = "Y";
    PredefinedEncoding.m_macRomanEncoding.names[90] = "Z";
    PredefinedEncoding.m_macRomanEncoding.names[91] = "bracketleft";
    PredefinedEncoding.m_macRomanEncoding.names[92] = "backslash";
    PredefinedEncoding.m_macRomanEncoding.names[93] = "bracketright";
    PredefinedEncoding.m_macRomanEncoding.names[94] = "asciicircum";
    PredefinedEncoding.m_macRomanEncoding.names[95] = "underscore";
    PredefinedEncoding.m_macRomanEncoding.names[96 /*0x60*/] = "grave";
    PredefinedEncoding.m_macRomanEncoding.names[97] = "a";
    PredefinedEncoding.m_macRomanEncoding.names[98] = "b";
    PredefinedEncoding.m_macRomanEncoding.names[99] = "c";
    PredefinedEncoding.m_macRomanEncoding.InitMapping();
  }

  private static void InitializePdfEncoding()
  {
    PredefinedEncoding.m_pdfdocEncoding = new PredefinedEncoding();
    PredefinedEncoding.m_pdfdocEncoding.Init();
    PredefinedEncoding.m_pdfdocEncoding.names[130] = "adblgrave";
    PredefinedEncoding.m_pdfdocEncoding.names[100] = "d";
    PredefinedEncoding.m_pdfdocEncoding.names[101] = "e";
    PredefinedEncoding.m_pdfdocEncoding.names[102] = "f";
    PredefinedEncoding.m_pdfdocEncoding.names[103] = "g";
    PredefinedEncoding.m_pdfdocEncoding.names[104] = "h";
    PredefinedEncoding.m_pdfdocEncoding.names[105] = "i";
    PredefinedEncoding.m_pdfdocEncoding.names[106] = "j";
    PredefinedEncoding.m_pdfdocEncoding.names[107] = "k";
    PredefinedEncoding.m_pdfdocEncoding.names[108] = "l";
    PredefinedEncoding.m_pdfdocEncoding.names[109] = "m";
    PredefinedEncoding.m_pdfdocEncoding.names[110] = "n";
    PredefinedEncoding.m_pdfdocEncoding.names[111] = "o";
    PredefinedEncoding.m_pdfdocEncoding.names[112 /*0x70*/] = "p";
    PredefinedEncoding.m_pdfdocEncoding.names[113] = "q";
    PredefinedEncoding.m_pdfdocEncoding.names[114] = "r";
    PredefinedEncoding.m_pdfdocEncoding.names[115] = "s";
    PredefinedEncoding.m_pdfdocEncoding.names[116] = "t";
    PredefinedEncoding.m_pdfdocEncoding.names[117] = "u";
    PredefinedEncoding.m_pdfdocEncoding.names[118] = "v";
    PredefinedEncoding.m_pdfdocEncoding.names[119] = "w";
    PredefinedEncoding.m_pdfdocEncoding.names[120] = "x";
    PredefinedEncoding.m_pdfdocEncoding.names[121] = "y";
    PredefinedEncoding.m_pdfdocEncoding.names[122] = "z";
    PredefinedEncoding.m_pdfdocEncoding.names[123] = "braceleft";
    PredefinedEncoding.m_pdfdocEncoding.names[124] = "bar";
    PredefinedEncoding.m_pdfdocEncoding.names[125] = "braceright";
    PredefinedEncoding.m_pdfdocEncoding.names[126] = "asciitilde";
    PredefinedEncoding.m_pdfdocEncoding.names[128 /*0x80*/] = "bullet";
    PredefinedEncoding.m_pdfdocEncoding.names[129] = "dagger";
    PredefinedEncoding.m_pdfdocEncoding.names[131] = "ellipsis";
    PredefinedEncoding.m_pdfdocEncoding.names[132] = "emdash";
    PredefinedEncoding.m_pdfdocEncoding.names[133] = "endash";
    PredefinedEncoding.m_pdfdocEncoding.names[134] = "florin";
    PredefinedEncoding.m_pdfdocEncoding.names[135] = "fraction";
    PredefinedEncoding.m_pdfdocEncoding.names[136] = "guilsinglleft";
    PredefinedEncoding.m_pdfdocEncoding.names[137] = "guilsinglright";
    PredefinedEncoding.m_pdfdocEncoding.names[138] = "minus";
    PredefinedEncoding.m_pdfdocEncoding.names[139] = "perthousand";
    PredefinedEncoding.m_pdfdocEncoding.names[140] = "quotedblbase";
    PredefinedEncoding.m_pdfdocEncoding.names[141] = "quotedblleft";
    PredefinedEncoding.m_pdfdocEncoding.names[142] = "quotedblright";
    PredefinedEncoding.m_pdfdocEncoding.names[143] = "quoteleft";
    PredefinedEncoding.m_pdfdocEncoding.names[144 /*0x90*/] = "quoteright";
    PredefinedEncoding.m_pdfdocEncoding.names[145] = "quotesinglbase";
    PredefinedEncoding.m_pdfdocEncoding.names[146] = "trademark";
    PredefinedEncoding.m_pdfdocEncoding.names[147] = "fi";
    PredefinedEncoding.m_pdfdocEncoding.names[148] = "fl";
    PredefinedEncoding.m_pdfdocEncoding.names[149] = "Lslash";
    PredefinedEncoding.m_pdfdocEncoding.names[150] = "OE";
    PredefinedEncoding.m_pdfdocEncoding.names[151] = "Scaron";
    PredefinedEncoding.m_pdfdocEncoding.names[152] = "Ydieresis";
    PredefinedEncoding.m_pdfdocEncoding.names[153] = "Zcaron";
    PredefinedEncoding.m_pdfdocEncoding.names[154] = "dotlessi";
    PredefinedEncoding.m_pdfdocEncoding.names[155] = "lslash";
    PredefinedEncoding.m_pdfdocEncoding.names[156] = "oe";
    PredefinedEncoding.m_pdfdocEncoding.names[157] = "scaron";
    PredefinedEncoding.m_pdfdocEncoding.names[158] = "zcaron";
    PredefinedEncoding.m_pdfdocEncoding.names[160 /*0xA0*/] = "Euro";
    PredefinedEncoding.m_pdfdocEncoding.names[161] = "exclamdown";
    PredefinedEncoding.m_pdfdocEncoding.names[162] = "cent";
    PredefinedEncoding.m_pdfdocEncoding.names[163] = "sterling";
    PredefinedEncoding.m_pdfdocEncoding.names[164] = "currency";
    PredefinedEncoding.m_pdfdocEncoding.names[165] = "yen";
    PredefinedEncoding.m_pdfdocEncoding.names[166] = "brokenbar";
    PredefinedEncoding.m_pdfdocEncoding.names[167] = "section";
    PredefinedEncoding.m_pdfdocEncoding.names[168] = "dieresis";
    PredefinedEncoding.m_pdfdocEncoding.names[169] = "copyright";
    PredefinedEncoding.m_pdfdocEncoding.names[170] = "ordfeminine";
    PredefinedEncoding.m_pdfdocEncoding.names[171] = "guillemotleft";
    PredefinedEncoding.m_pdfdocEncoding.names[172] = "logicalnot";
    PredefinedEncoding.m_pdfdocEncoding.names[174] = "registered";
    PredefinedEncoding.m_pdfdocEncoding.names[175] = "macron";
    PredefinedEncoding.m_pdfdocEncoding.names[176 /*0xB0*/] = "degree";
    PredefinedEncoding.m_pdfdocEncoding.names[177] = "plusminus";
    PredefinedEncoding.m_pdfdocEncoding.names[178] = "twosuperior";
    PredefinedEncoding.m_pdfdocEncoding.names[179] = "threesuperior";
    PredefinedEncoding.m_pdfdocEncoding.names[180] = "acute";
    PredefinedEncoding.m_pdfdocEncoding.names[181] = "mu";
    PredefinedEncoding.m_pdfdocEncoding.names[182] = "paragraph";
    PredefinedEncoding.m_pdfdocEncoding.names[183] = "middot";
    PredefinedEncoding.m_pdfdocEncoding.names[184] = "cedilla";
    PredefinedEncoding.m_pdfdocEncoding.names[185] = "onesuperior";
    PredefinedEncoding.m_pdfdocEncoding.names[186] = "ordmasculine";
    PredefinedEncoding.m_pdfdocEncoding.names[187] = "guillemotright";
    PredefinedEncoding.m_pdfdocEncoding.names[188] = "onequarter";
    PredefinedEncoding.m_pdfdocEncoding.names[189] = "onehalf";
    PredefinedEncoding.m_pdfdocEncoding.names[190] = "threequarters";
    PredefinedEncoding.m_pdfdocEncoding.names[191] = "questiondown";
    PredefinedEncoding.m_pdfdocEncoding.names[192 /*0xC0*/] = "Agrave";
    PredefinedEncoding.m_pdfdocEncoding.names[193] = "Aacute";
    PredefinedEncoding.m_pdfdocEncoding.names[194] = "Acircumflex";
    PredefinedEncoding.m_pdfdocEncoding.names[195] = "Atilde";
    PredefinedEncoding.m_pdfdocEncoding.names[196] = "Adieresis";
    PredefinedEncoding.m_pdfdocEncoding.names[197] = "Aring";
    PredefinedEncoding.m_pdfdocEncoding.names[198] = "AE";
    PredefinedEncoding.m_pdfdocEncoding.names[199] = "Ccedilla";
    PredefinedEncoding.m_pdfdocEncoding.names[200] = "Egrave";
    PredefinedEncoding.m_pdfdocEncoding.names[201] = "Eacute";
    PredefinedEncoding.m_pdfdocEncoding.names[202] = "Ecircumflex";
    PredefinedEncoding.m_pdfdocEncoding.names[203] = "Edieresis";
    PredefinedEncoding.m_pdfdocEncoding.names[204] = "Igrave";
    PredefinedEncoding.m_pdfdocEncoding.names[205] = "Iacute";
    PredefinedEncoding.m_pdfdocEncoding.names[206] = "Icircumflex";
    PredefinedEncoding.m_pdfdocEncoding.names[207] = "Idieresis";
    PredefinedEncoding.m_pdfdocEncoding.names[208 /*0xD0*/] = "Eth";
    PredefinedEncoding.m_pdfdocEncoding.names[210] = "Ntilde";
    PredefinedEncoding.m_pdfdocEncoding.names[211] = "Oacute";
    PredefinedEncoding.m_pdfdocEncoding.names[212] = "Ocircumflex";
    PredefinedEncoding.m_pdfdocEncoding.names[213] = "Otilde";
    PredefinedEncoding.m_pdfdocEncoding.names[214] = "Odieresis";
    PredefinedEncoding.m_pdfdocEncoding.names[215] = "multiply";
    PredefinedEncoding.m_pdfdocEncoding.names[216] = "Oslash";
    PredefinedEncoding.m_pdfdocEncoding.names[217] = "Ugrave";
    PredefinedEncoding.m_pdfdocEncoding.names[218] = "Uacute";
    PredefinedEncoding.m_pdfdocEncoding.names[219] = "Ucircumflex";
    PredefinedEncoding.m_pdfdocEncoding.names[220] = "Udieresis";
    PredefinedEncoding.m_pdfdocEncoding.names[221] = "Yacute";
    PredefinedEncoding.m_pdfdocEncoding.names[222] = "Thorn";
    PredefinedEncoding.m_pdfdocEncoding.names[223] = "germandbls";
    PredefinedEncoding.m_pdfdocEncoding.names[224 /*0xE0*/] = "agrave";
    PredefinedEncoding.m_pdfdocEncoding.names[225] = "aacute";
    PredefinedEncoding.m_pdfdocEncoding.names[226] = "acircumflex";
    PredefinedEncoding.m_pdfdocEncoding.names[227] = "atilde";
    PredefinedEncoding.m_pdfdocEncoding.names[228] = "adieresis";
    PredefinedEncoding.m_pdfdocEncoding.names[229] = "aring";
    PredefinedEncoding.m_pdfdocEncoding.names[230] = "ae";
    PredefinedEncoding.m_pdfdocEncoding.names[231] = "ccedilla";
    PredefinedEncoding.m_pdfdocEncoding.names[232] = "egrave";
    PredefinedEncoding.m_pdfdocEncoding.names[233] = "eacute";
    PredefinedEncoding.m_pdfdocEncoding.names[234] = "ecircumflex";
    PredefinedEncoding.m_pdfdocEncoding.names[235] = "edieresis";
    PredefinedEncoding.m_pdfdocEncoding.names[236] = "igrave";
    PredefinedEncoding.m_pdfdocEncoding.names[237] = "iacute";
    PredefinedEncoding.m_pdfdocEncoding.names[238] = "icircumflex";
    PredefinedEncoding.m_pdfdocEncoding.names[239] = "idieresis";
    PredefinedEncoding.m_pdfdocEncoding.names[24] = "breve";
    PredefinedEncoding.m_pdfdocEncoding.names[240 /*0xF0*/] = "eth";
    PredefinedEncoding.m_pdfdocEncoding.names[241] = "ntilde";
    PredefinedEncoding.m_pdfdocEncoding.names[242] = "ograve";
    PredefinedEncoding.m_pdfdocEncoding.names[243] = "oacute";
    PredefinedEncoding.m_pdfdocEncoding.names[244] = "ocircumflex";
    PredefinedEncoding.m_pdfdocEncoding.names[245] = "otilde";
    PredefinedEncoding.m_pdfdocEncoding.names[246] = "odieresis";
    PredefinedEncoding.m_pdfdocEncoding.names[247] = "divide";
    PredefinedEncoding.m_pdfdocEncoding.names[248] = "oslash";
    PredefinedEncoding.m_pdfdocEncoding.names[249] = "ugrave";
    PredefinedEncoding.m_pdfdocEncoding.names[25] = "caron";
    PredefinedEncoding.m_pdfdocEncoding.names[250] = "uacute";
    PredefinedEncoding.m_pdfdocEncoding.names[251] = "ucircumflex";
    PredefinedEncoding.m_pdfdocEncoding.names[252] = "udieresis";
    PredefinedEncoding.m_pdfdocEncoding.names[253] = "yacute";
    PredefinedEncoding.m_pdfdocEncoding.names[254] = "thorn";
    PredefinedEncoding.m_pdfdocEncoding.names[(int) byte.MaxValue] = "ydieresis";
    PredefinedEncoding.m_pdfdocEncoding.names[26] = "circumflex";
    PredefinedEncoding.m_pdfdocEncoding.names[27] = "dotaccent";
    PredefinedEncoding.m_pdfdocEncoding.names[28] = "hungarumlaut";
    PredefinedEncoding.m_pdfdocEncoding.names[29] = "ogonek";
    PredefinedEncoding.m_pdfdocEncoding.names[30] = "ring";
    PredefinedEncoding.m_pdfdocEncoding.names[31 /*0x1F*/] = "ilde";
    PredefinedEncoding.m_pdfdocEncoding.names[32 /*0x20*/] = "space";
    PredefinedEncoding.m_pdfdocEncoding.names[33] = "exclam";
    PredefinedEncoding.m_pdfdocEncoding.names[34] = "quotedbl";
    PredefinedEncoding.m_pdfdocEncoding.names[35] = "numbersign";
    PredefinedEncoding.m_pdfdocEncoding.names[36] = "dollar";
    PredefinedEncoding.m_pdfdocEncoding.names[37] = "percent";
    PredefinedEncoding.m_pdfdocEncoding.names[38] = "ampersand";
    PredefinedEncoding.m_pdfdocEncoding.names[39] = "quotesingle";
    PredefinedEncoding.m_pdfdocEncoding.names[40] = "parenleft";
    PredefinedEncoding.m_pdfdocEncoding.names[41] = "parenright";
    PredefinedEncoding.m_pdfdocEncoding.names[42] = "asterisk";
    PredefinedEncoding.m_pdfdocEncoding.names[43] = "plus";
    PredefinedEncoding.m_pdfdocEncoding.names[44] = "comma";
    PredefinedEncoding.m_pdfdocEncoding.names[45] = "hyphen";
    PredefinedEncoding.m_pdfdocEncoding.names[46] = "period";
    PredefinedEncoding.m_pdfdocEncoding.names[47] = "slash";
    PredefinedEncoding.m_pdfdocEncoding.names[48 /*0x30*/] = "zero";
    PredefinedEncoding.m_pdfdocEncoding.names[49] = "one";
    PredefinedEncoding.m_pdfdocEncoding.names[50] = "two";
    PredefinedEncoding.m_pdfdocEncoding.names[51] = "three";
    PredefinedEncoding.m_pdfdocEncoding.names[52] = "four";
    PredefinedEncoding.m_pdfdocEncoding.names[53] = "five";
    PredefinedEncoding.m_pdfdocEncoding.names[54] = "six";
    PredefinedEncoding.m_pdfdocEncoding.names[55] = "seven";
    PredefinedEncoding.m_pdfdocEncoding.names[56] = "eight";
    PredefinedEncoding.m_pdfdocEncoding.names[57] = "nine";
    PredefinedEncoding.m_pdfdocEncoding.names[58] = "colon";
    PredefinedEncoding.m_pdfdocEncoding.names[59] = "semicolon";
    PredefinedEncoding.m_pdfdocEncoding.names[60] = "less";
    PredefinedEncoding.m_pdfdocEncoding.names[61] = "equal";
    PredefinedEncoding.m_pdfdocEncoding.names[62] = "greater";
    PredefinedEncoding.m_pdfdocEncoding.names[63 /*0x3F*/] = "question";
    PredefinedEncoding.m_pdfdocEncoding.names[64 /*0x40*/] = "at";
    PredefinedEncoding.m_pdfdocEncoding.names[65] = "A";
    PredefinedEncoding.m_pdfdocEncoding.names[66] = "B";
    PredefinedEncoding.m_pdfdocEncoding.names[67] = "C";
    PredefinedEncoding.m_pdfdocEncoding.names[68] = "D";
    PredefinedEncoding.m_pdfdocEncoding.names[69] = "E";
    PredefinedEncoding.m_pdfdocEncoding.names[70] = "F";
    PredefinedEncoding.m_pdfdocEncoding.names[71] = "G";
    PredefinedEncoding.m_pdfdocEncoding.names[72] = "H";
    PredefinedEncoding.m_pdfdocEncoding.names[73] = "I";
    PredefinedEncoding.m_pdfdocEncoding.names[74] = "J";
    PredefinedEncoding.m_pdfdocEncoding.names[75] = "K";
    PredefinedEncoding.m_pdfdocEncoding.names[76] = "L";
    PredefinedEncoding.m_pdfdocEncoding.names[77] = "M";
    PredefinedEncoding.m_pdfdocEncoding.names[78] = "N";
    PredefinedEncoding.m_pdfdocEncoding.names[79] = "O";
    PredefinedEncoding.m_pdfdocEncoding.names[80 /*0x50*/] = "P";
    PredefinedEncoding.m_pdfdocEncoding.names[81] = "Q";
    PredefinedEncoding.m_pdfdocEncoding.names[82] = "R";
    PredefinedEncoding.m_pdfdocEncoding.names[83] = "S";
    PredefinedEncoding.m_pdfdocEncoding.names[84] = "T";
    PredefinedEncoding.m_pdfdocEncoding.names[85] = "U";
    PredefinedEncoding.m_pdfdocEncoding.names[86] = "V";
    PredefinedEncoding.m_pdfdocEncoding.names[87] = "W";
    PredefinedEncoding.m_pdfdocEncoding.names[88] = "X";
    PredefinedEncoding.m_pdfdocEncoding.names[89] = "Y";
    PredefinedEncoding.m_pdfdocEncoding.names[90] = "Z";
    PredefinedEncoding.m_pdfdocEncoding.names[91] = "bracketleft";
    PredefinedEncoding.m_pdfdocEncoding.names[92] = "backslash";
    PredefinedEncoding.m_pdfdocEncoding.names[93] = "bracketright";
    PredefinedEncoding.m_pdfdocEncoding.names[94] = "asciicircum";
    PredefinedEncoding.m_pdfdocEncoding.names[95] = "underscore";
    PredefinedEncoding.m_pdfdocEncoding.names[96 /*0x60*/] = "grave";
    PredefinedEncoding.m_pdfdocEncoding.names[97] = "a";
    PredefinedEncoding.m_pdfdocEncoding.names[98] = "b";
    PredefinedEncoding.m_pdfdocEncoding.names[99] = "c";
    PredefinedEncoding.m_pdfdocEncoding.InitMapping();
  }

  private static void InitializeStandardMacEncoding()
  {
    PredefinedEncoding.StandardMacRomanEncoding = new PredefinedEncoding();
    PredefinedEncoding.m_standardMacRomanEncoding.Init();
    PredefinedEncoding.m_standardMacRomanEncoding.m_name = "MacRomanEncoding";
    PredefinedEncoding.StandardMacRomanEncoding.names[224 /*0xE0*/] = "adblgrave";
    PredefinedEncoding.m_standardMacRomanEncoding.names[100] = "d";
    PredefinedEncoding.m_standardMacRomanEncoding.names[101] = "e";
    PredefinedEncoding.m_standardMacRomanEncoding.names[102] = "f";
    PredefinedEncoding.m_standardMacRomanEncoding.names[103] = "g";
    PredefinedEncoding.m_standardMacRomanEncoding.names[104] = "h";
    PredefinedEncoding.m_standardMacRomanEncoding.names[105] = "i";
    PredefinedEncoding.m_standardMacRomanEncoding.names[106] = "j";
    PredefinedEncoding.m_standardMacRomanEncoding.names[107] = "k";
    PredefinedEncoding.m_standardMacRomanEncoding.names[108] = "l";
    PredefinedEncoding.m_standardMacRomanEncoding.names[109] = "m";
    PredefinedEncoding.m_standardMacRomanEncoding.names[110] = "n";
    PredefinedEncoding.m_standardMacRomanEncoding.names[111] = "o";
    PredefinedEncoding.m_standardMacRomanEncoding.names[112 /*0x70*/] = "p";
    PredefinedEncoding.m_standardMacRomanEncoding.names[113] = "q";
    PredefinedEncoding.m_standardMacRomanEncoding.names[114] = "r";
    PredefinedEncoding.m_standardMacRomanEncoding.names[115] = "s";
    PredefinedEncoding.m_standardMacRomanEncoding.names[116] = "t";
    PredefinedEncoding.m_standardMacRomanEncoding.names[117] = "u";
    PredefinedEncoding.m_standardMacRomanEncoding.names[118] = "v";
    PredefinedEncoding.m_standardMacRomanEncoding.names[119] = "w";
    PredefinedEncoding.m_standardMacRomanEncoding.names[120] = "x";
    PredefinedEncoding.m_standardMacRomanEncoding.names[121] = "y";
    PredefinedEncoding.m_standardMacRomanEncoding.names[122] = "z";
    PredefinedEncoding.m_standardMacRomanEncoding.names[123] = "braceleft";
    PredefinedEncoding.m_standardMacRomanEncoding.names[124] = "bar";
    PredefinedEncoding.m_standardMacRomanEncoding.names[125] = "braceright";
    PredefinedEncoding.m_standardMacRomanEncoding.names[126] = "asciitilde";
    PredefinedEncoding.m_standardMacRomanEncoding.names[128 /*0x80*/] = "Adieresis";
    PredefinedEncoding.m_standardMacRomanEncoding.names[129] = "Aring";
    PredefinedEncoding.m_standardMacRomanEncoding.names[130] = "Ccedilla";
    PredefinedEncoding.m_standardMacRomanEncoding.names[131] = "Eacute";
    PredefinedEncoding.m_standardMacRomanEncoding.names[132] = "Ograve";
    PredefinedEncoding.m_standardMacRomanEncoding.names[133] = "Odieresis";
    PredefinedEncoding.m_standardMacRomanEncoding.names[134] = "Udieresis";
    PredefinedEncoding.m_standardMacRomanEncoding.names[135] = "aacute";
    PredefinedEncoding.m_standardMacRomanEncoding.names[137] = "acircumflex";
    PredefinedEncoding.m_standardMacRomanEncoding.names[137] = "agrave";
    PredefinedEncoding.m_standardMacRomanEncoding.names[138] = "adieresis";
    PredefinedEncoding.m_standardMacRomanEncoding.names[139] = "atilde";
    PredefinedEncoding.m_standardMacRomanEncoding.names[140] = "aring";
    PredefinedEncoding.m_standardMacRomanEncoding.names[141] = "ccedilla";
    PredefinedEncoding.m_standardMacRomanEncoding.names[142] = "eacute";
    PredefinedEncoding.m_standardMacRomanEncoding.names[143] = "egrave";
    PredefinedEncoding.m_standardMacRomanEncoding.names[144 /*0x90*/] = "ecircumflex";
    PredefinedEncoding.m_standardMacRomanEncoding.names[145] = "edieresis";
    PredefinedEncoding.m_standardMacRomanEncoding.names[146] = "iacute";
    PredefinedEncoding.m_standardMacRomanEncoding.names[147] = "igrave";
    PredefinedEncoding.m_standardMacRomanEncoding.names[148] = "icircumflex";
    PredefinedEncoding.m_standardMacRomanEncoding.names[149] = "idieresis";
    PredefinedEncoding.m_standardMacRomanEncoding.names[150] = "ntilde";
    PredefinedEncoding.m_standardMacRomanEncoding.names[151] = "oacute";
    PredefinedEncoding.m_standardMacRomanEncoding.names[152] = "ograve";
    PredefinedEncoding.m_standardMacRomanEncoding.names[153] = "ocircumflex";
    PredefinedEncoding.m_standardMacRomanEncoding.names[154] = "odieresis";
    PredefinedEncoding.m_standardMacRomanEncoding.names[155] = "otilde";
    PredefinedEncoding.m_standardMacRomanEncoding.names[156] = "uacute";
    PredefinedEncoding.m_standardMacRomanEncoding.names[157] = "ugrave";
    PredefinedEncoding.m_standardMacRomanEncoding.names[158] = "ucircumflex";
    PredefinedEncoding.m_standardMacRomanEncoding.names[159] = "udieresis";
    PredefinedEncoding.m_standardMacRomanEncoding.names[160 /*0xA0*/] = "dagger";
    PredefinedEncoding.m_standardMacRomanEncoding.names[161] = "degree";
    PredefinedEncoding.m_standardMacRomanEncoding.names[162] = "cent";
    PredefinedEncoding.m_standardMacRomanEncoding.names[163] = "sterling";
    PredefinedEncoding.m_standardMacRomanEncoding.names[164] = "section";
    PredefinedEncoding.m_standardMacRomanEncoding.names[165] = "bullet";
    PredefinedEncoding.m_standardMacRomanEncoding.names[166] = "paragraph";
    PredefinedEncoding.m_standardMacRomanEncoding.names[167] = "germandbls";
    PredefinedEncoding.m_standardMacRomanEncoding.names[168] = "registered";
    PredefinedEncoding.m_standardMacRomanEncoding.names[169] = "copyright";
    PredefinedEncoding.m_standardMacRomanEncoding.names[170] = "trademark";
    PredefinedEncoding.m_standardMacRomanEncoding.names[171] = "acute";
    PredefinedEncoding.m_standardMacRomanEncoding.names[172] = "dieresis";
    PredefinedEncoding.m_standardMacRomanEncoding.names[174] = "AE";
    PredefinedEncoding.m_standardMacRomanEncoding.names[175] = "Oslash";
    PredefinedEncoding.m_standardMacRomanEncoding.names[177] = "plusminus";
    PredefinedEncoding.m_standardMacRomanEncoding.names[180] = "yen";
    PredefinedEncoding.m_standardMacRomanEncoding.names[181] = "mu";
    PredefinedEncoding.m_standardMacRomanEncoding.names[187] = "ordfeminine";
    PredefinedEncoding.m_standardMacRomanEncoding.names[188] = "ordmasculine";
    PredefinedEncoding.m_standardMacRomanEncoding.names[190] = "ae";
    PredefinedEncoding.m_standardMacRomanEncoding.names[191] = "oslash";
    PredefinedEncoding.m_standardMacRomanEncoding.names[192 /*0xC0*/] = "questiondown";
    PredefinedEncoding.m_standardMacRomanEncoding.names[193] = "exclamdown";
    PredefinedEncoding.m_standardMacRomanEncoding.names[194] = "logicalnot";
    PredefinedEncoding.m_standardMacRomanEncoding.names[196] = "florin";
    PredefinedEncoding.m_standardMacRomanEncoding.names[199] = "guillemotleft";
    PredefinedEncoding.m_standardMacRomanEncoding.names[200] = "guillemotright";
    PredefinedEncoding.m_standardMacRomanEncoding.names[201] = "ellipsis";
    PredefinedEncoding.m_standardMacRomanEncoding.names[203] = "Agrave";
    PredefinedEncoding.m_standardMacRomanEncoding.names[204] = "Atilde";
    PredefinedEncoding.m_standardMacRomanEncoding.names[205] = "Otilde";
    PredefinedEncoding.m_standardMacRomanEncoding.names[206] = "OE";
    PredefinedEncoding.m_standardMacRomanEncoding.names[207] = "oe";
    PredefinedEncoding.m_standardMacRomanEncoding.names[208 /*0xD0*/] = "endash";
    PredefinedEncoding.m_standardMacRomanEncoding.names[209] = "emdash";
    PredefinedEncoding.m_standardMacRomanEncoding.names[210] = "quotedblleft";
    PredefinedEncoding.m_standardMacRomanEncoding.names[211] = "quotedblright";
    PredefinedEncoding.m_standardMacRomanEncoding.names[212] = "quoteleft";
    PredefinedEncoding.m_standardMacRomanEncoding.names[213] = "quoteright";
    PredefinedEncoding.m_standardMacRomanEncoding.names[214] = "divide";
    PredefinedEncoding.m_standardMacRomanEncoding.names[216] = "ydieresis";
    PredefinedEncoding.m_standardMacRomanEncoding.names[217] = "Ydieresis";
    PredefinedEncoding.m_standardMacRomanEncoding.names[218] = "fraction";
    PredefinedEncoding.m_standardMacRomanEncoding.names[220] = "guilsinglleft";
    PredefinedEncoding.m_standardMacRomanEncoding.names[221] = "guilsinglright";
    PredefinedEncoding.m_standardMacRomanEncoding.names[222] = "fi";
    PredefinedEncoding.m_standardMacRomanEncoding.names[223] = "fl";
    PredefinedEncoding.m_standardMacRomanEncoding.names[225] = "middot";
    PredefinedEncoding.m_standardMacRomanEncoding.names[226] = "quotesinglbase";
    PredefinedEncoding.m_standardMacRomanEncoding.names[227] = "quotedblbase";
    PredefinedEncoding.m_standardMacRomanEncoding.names[228] = "perthousand";
    PredefinedEncoding.m_standardMacRomanEncoding.names[229] = "Acircumflex";
    PredefinedEncoding.m_standardMacRomanEncoding.names[230] = "Ecircumflex";
    PredefinedEncoding.m_standardMacRomanEncoding.names[231] = "Aacute";
    PredefinedEncoding.m_standardMacRomanEncoding.names[232] = "Edieresis";
    PredefinedEncoding.m_standardMacRomanEncoding.names[233] = "Egrave";
    PredefinedEncoding.m_standardMacRomanEncoding.names[234] = "Iacute";
    PredefinedEncoding.m_standardMacRomanEncoding.names[235] = "Icircumflex";
    PredefinedEncoding.m_standardMacRomanEncoding.names[236] = "Idieresis";
    PredefinedEncoding.m_standardMacRomanEncoding.names[237] = "Igrave";
    PredefinedEncoding.m_standardMacRomanEncoding.names[238] = "Oacute";
    PredefinedEncoding.m_standardMacRomanEncoding.names[239] = "Ocircumflex";
    PredefinedEncoding.m_standardMacRomanEncoding.names[241] = "Ntilde";
    PredefinedEncoding.m_standardMacRomanEncoding.names[242] = "Uacute";
    PredefinedEncoding.m_standardMacRomanEncoding.names[243] = "Ucircumflex";
    PredefinedEncoding.m_standardMacRomanEncoding.names[244] = "Ugrave";
    PredefinedEncoding.m_standardMacRomanEncoding.names[245] = "dotlessi";
    PredefinedEncoding.m_standardMacRomanEncoding.names[246] = "circumflex";
    PredefinedEncoding.m_standardMacRomanEncoding.names[247] = "ilde";
    PredefinedEncoding.m_standardMacRomanEncoding.names[248] = "macron";
    PredefinedEncoding.m_standardMacRomanEncoding.names[249] = "breve";
    PredefinedEncoding.m_standardMacRomanEncoding.names[250] = "dotaccent";
    PredefinedEncoding.m_standardMacRomanEncoding.names[251] = "ring";
    PredefinedEncoding.m_standardMacRomanEncoding.names[252] = "cedilla";
    PredefinedEncoding.m_standardMacRomanEncoding.names[253] = "hungarumlaut";
    PredefinedEncoding.m_standardMacRomanEncoding.names[254] = "ogonek";
    PredefinedEncoding.m_standardMacRomanEncoding.names[(int) byte.MaxValue] = "caron";
    PredefinedEncoding.m_standardMacRomanEncoding.names[32 /*0x20*/] = "space";
    PredefinedEncoding.m_standardMacRomanEncoding.names[33] = "exclam";
    PredefinedEncoding.m_standardMacRomanEncoding.names[34] = "quotedbl";
    PredefinedEncoding.m_standardMacRomanEncoding.names[35] = "numbersign";
    PredefinedEncoding.m_standardMacRomanEncoding.names[36] = "dollar";
    PredefinedEncoding.m_standardMacRomanEncoding.names[37] = "percent";
    PredefinedEncoding.m_standardMacRomanEncoding.names[38] = "ampersand";
    PredefinedEncoding.m_standardMacRomanEncoding.names[39] = "quotesingle";
    PredefinedEncoding.m_standardMacRomanEncoding.names[40] = "parenleft";
    PredefinedEncoding.m_standardMacRomanEncoding.names[41] = "parenright";
    PredefinedEncoding.m_standardMacRomanEncoding.names[42] = "asterisk";
    PredefinedEncoding.m_standardMacRomanEncoding.names[43] = "plus";
    PredefinedEncoding.m_standardMacRomanEncoding.names[44] = "comma";
    PredefinedEncoding.m_standardMacRomanEncoding.names[45] = "hyphen";
    PredefinedEncoding.m_standardMacRomanEncoding.names[46] = "period";
    PredefinedEncoding.m_standardMacRomanEncoding.names[47] = "slash";
    PredefinedEncoding.m_standardMacRomanEncoding.names[48 /*0x30*/] = "zero";
    PredefinedEncoding.m_standardMacRomanEncoding.names[49] = "one";
    PredefinedEncoding.m_standardMacRomanEncoding.names[50] = "two";
    PredefinedEncoding.m_standardMacRomanEncoding.names[51] = "three";
    PredefinedEncoding.m_standardMacRomanEncoding.names[52] = "four";
    PredefinedEncoding.m_standardMacRomanEncoding.names[53] = "five";
    PredefinedEncoding.m_standardMacRomanEncoding.names[54] = "six";
    PredefinedEncoding.m_standardMacRomanEncoding.names[55] = "seven";
    PredefinedEncoding.m_standardMacRomanEncoding.names[56] = "eight";
    PredefinedEncoding.m_standardMacRomanEncoding.names[57] = "nine";
    PredefinedEncoding.m_standardMacRomanEncoding.names[58] = "colon";
    PredefinedEncoding.m_standardMacRomanEncoding.names[59] = "semicolon";
    PredefinedEncoding.m_standardMacRomanEncoding.names[60] = "less";
    PredefinedEncoding.m_standardMacRomanEncoding.names[61] = "equal";
    PredefinedEncoding.m_standardMacRomanEncoding.names[62] = "greater";
    PredefinedEncoding.m_standardMacRomanEncoding.names[63 /*0x3F*/] = "question";
    PredefinedEncoding.m_standardMacRomanEncoding.names[64 /*0x40*/] = "at";
    PredefinedEncoding.m_standardMacRomanEncoding.names[65] = "A";
    PredefinedEncoding.m_standardMacRomanEncoding.names[66] = "B";
    PredefinedEncoding.m_standardMacRomanEncoding.names[67] = "C";
    PredefinedEncoding.m_standardMacRomanEncoding.names[68] = "D";
    PredefinedEncoding.m_standardMacRomanEncoding.names[69] = "E";
    PredefinedEncoding.m_standardMacRomanEncoding.names[70] = "F";
    PredefinedEncoding.m_standardMacRomanEncoding.names[71] = "G";
    PredefinedEncoding.m_standardMacRomanEncoding.names[72] = "H";
    PredefinedEncoding.m_standardMacRomanEncoding.names[73] = "I";
    PredefinedEncoding.m_standardMacRomanEncoding.names[74] = "J";
    PredefinedEncoding.m_standardMacRomanEncoding.names[75] = "K";
    PredefinedEncoding.m_standardMacRomanEncoding.names[76] = "L";
    PredefinedEncoding.m_standardMacRomanEncoding.names[77] = "M";
    PredefinedEncoding.m_standardMacRomanEncoding.names[78] = "N";
    PredefinedEncoding.m_standardMacRomanEncoding.names[79] = "O";
    PredefinedEncoding.m_standardMacRomanEncoding.names[80 /*0x50*/] = "P";
    PredefinedEncoding.m_standardMacRomanEncoding.names[81] = "Q";
    PredefinedEncoding.m_standardMacRomanEncoding.names[82] = "R";
    PredefinedEncoding.m_standardMacRomanEncoding.names[83] = "S";
    PredefinedEncoding.m_standardMacRomanEncoding.names[84] = "T";
    PredefinedEncoding.m_standardMacRomanEncoding.names[85] = "U";
    PredefinedEncoding.m_standardMacRomanEncoding.names[86] = "V";
    PredefinedEncoding.m_standardMacRomanEncoding.names[87] = "W";
    PredefinedEncoding.m_standardMacRomanEncoding.names[88] = "X";
    PredefinedEncoding.m_standardMacRomanEncoding.names[89] = "Y";
    PredefinedEncoding.m_standardMacRomanEncoding.names[90] = "Z";
    PredefinedEncoding.m_standardMacRomanEncoding.names[91] = "bracketleft";
    PredefinedEncoding.m_standardMacRomanEncoding.names[92] = "backslash";
    PredefinedEncoding.m_standardMacRomanEncoding.names[93] = "bracketright";
    PredefinedEncoding.m_standardMacRomanEncoding.names[94] = "asciicircum";
    PredefinedEncoding.m_standardMacRomanEncoding.names[95] = "underscore";
    PredefinedEncoding.m_standardMacRomanEncoding.names[96 /*0x60*/] = "grave";
    PredefinedEncoding.m_standardMacRomanEncoding.names[97] = "a";
    PredefinedEncoding.m_standardMacRomanEncoding.names[98] = "b";
    PredefinedEncoding.m_standardMacRomanEncoding.names[99] = "c";
    PredefinedEncoding.m_standardMacRomanEncoding.names[173] = "notequal";
    PredefinedEncoding.m_standardMacRomanEncoding.names[176 /*0xB0*/] = "infinity";
    PredefinedEncoding.m_standardMacRomanEncoding.names[178] = "lessequal";
    PredefinedEncoding.m_standardMacRomanEncoding.names[179] = "greaterequal";
    PredefinedEncoding.m_standardMacRomanEncoding.names[182] = "partialdiff";
    PredefinedEncoding.m_standardMacRomanEncoding.names[183] = "summation";
    PredefinedEncoding.m_standardMacRomanEncoding.names[184] = "product";
    PredefinedEncoding.m_standardMacRomanEncoding.names[185] = "pi";
    PredefinedEncoding.m_standardMacRomanEncoding.names[186] = "integral";
    PredefinedEncoding.m_standardMacRomanEncoding.names[189] = "Omega";
    PredefinedEncoding.m_standardMacRomanEncoding.names[195] = "radical";
    PredefinedEncoding.m_standardMacRomanEncoding.names[197] = "approxequal";
    PredefinedEncoding.m_standardMacRomanEncoding.names[198] = "Delta";
    PredefinedEncoding.StandardMacRomanEncoding.names[215] = "lozenge";
    PredefinedEncoding.StandardMacRomanEncoding.names[219] = "Euro";
    PredefinedEncoding.m_standardMacRomanEncoding.names[240 /*0xF0*/] = "apple";
    PredefinedEncoding.m_standardMacRomanEncoding.InitMapping();
  }

  private static void InitializeWinAnsiEncoding()
  {
    PredefinedEncoding.m_winAnsiEncoding = new PredefinedEncoding();
    PredefinedEncoding.m_winAnsiEncoding.Init();
    PredefinedEncoding.m_winAnsiEncoding.m_name = "WinAnsiEncoding";
    PredefinedEncoding.m_winAnsiEncoding.names[173] = "hyphen";
    PredefinedEncoding.m_winAnsiEncoding.names[160 /*0xA0*/] = "space";
    PredefinedEncoding.m_winAnsiEncoding.names[135] = "adblgrave";
    PredefinedEncoding.m_winAnsiEncoding.names[100] = "d";
    PredefinedEncoding.m_winAnsiEncoding.names[101] = "e";
    PredefinedEncoding.m_winAnsiEncoding.names[102] = "f";
    PredefinedEncoding.m_winAnsiEncoding.names[103] = "g";
    PredefinedEncoding.m_winAnsiEncoding.names[104] = "h";
    PredefinedEncoding.m_winAnsiEncoding.names[105] = "i";
    PredefinedEncoding.m_winAnsiEncoding.names[106] = "j";
    PredefinedEncoding.m_winAnsiEncoding.names[107] = "k";
    PredefinedEncoding.m_winAnsiEncoding.names[108] = "l";
    PredefinedEncoding.m_winAnsiEncoding.names[109] = "m";
    PredefinedEncoding.m_winAnsiEncoding.names[110] = "n";
    PredefinedEncoding.m_winAnsiEncoding.names[111] = "o";
    PredefinedEncoding.m_winAnsiEncoding.names[112 /*0x70*/] = "p";
    PredefinedEncoding.m_winAnsiEncoding.names[113] = "q";
    PredefinedEncoding.m_winAnsiEncoding.names[114] = "r";
    PredefinedEncoding.m_winAnsiEncoding.names[115] = "s";
    PredefinedEncoding.m_winAnsiEncoding.names[116] = "t";
    PredefinedEncoding.m_winAnsiEncoding.names[117] = "u";
    PredefinedEncoding.m_winAnsiEncoding.names[118] = "v";
    PredefinedEncoding.m_winAnsiEncoding.names[119] = "w";
    PredefinedEncoding.m_winAnsiEncoding.names[120] = "x";
    PredefinedEncoding.m_winAnsiEncoding.names[121] = "y";
    PredefinedEncoding.m_winAnsiEncoding.names[122] = "z";
    PredefinedEncoding.m_winAnsiEncoding.names[123] = "braceleft";
    PredefinedEncoding.m_winAnsiEncoding.names[124] = "bar";
    PredefinedEncoding.m_winAnsiEncoding.names[125] = "braceright";
    PredefinedEncoding.m_winAnsiEncoding.names[126] = "asciitilde";
    PredefinedEncoding.m_winAnsiEncoding.names[128 /*0x80*/] = "Euro";
    PredefinedEncoding.m_winAnsiEncoding.names[130] = "quotesinglbase";
    PredefinedEncoding.m_winAnsiEncoding.names[131] = "florin";
    PredefinedEncoding.m_winAnsiEncoding.names[132] = "quotedblbase";
    PredefinedEncoding.m_winAnsiEncoding.names[133] = "ellipsis";
    PredefinedEncoding.m_winAnsiEncoding.names[134] = "dagger";
    PredefinedEncoding.m_winAnsiEncoding.names[136] = "circumflex";
    PredefinedEncoding.m_winAnsiEncoding.names[137] = "perthousand";
    PredefinedEncoding.m_winAnsiEncoding.names[138] = "Scaron";
    PredefinedEncoding.m_winAnsiEncoding.names[139] = "guilsinglleft";
    PredefinedEncoding.m_winAnsiEncoding.names[140] = "OE";
    PredefinedEncoding.m_winAnsiEncoding.names[142] = "Zcaron";
    PredefinedEncoding.m_winAnsiEncoding.names[145] = "quoteleft";
    PredefinedEncoding.m_winAnsiEncoding.names[146] = "quoteright";
    PredefinedEncoding.m_winAnsiEncoding.names[147] = "quotedblleft";
    PredefinedEncoding.m_winAnsiEncoding.names[148] = "quotedblright";
    PredefinedEncoding.m_winAnsiEncoding.names[149] = "bullet";
    PredefinedEncoding.m_winAnsiEncoding.names[150] = "endash";
    PredefinedEncoding.m_winAnsiEncoding.names[151] = "emdash";
    PredefinedEncoding.m_winAnsiEncoding.names[152] = "ilde";
    PredefinedEncoding.m_winAnsiEncoding.names[153] = "trademark";
    PredefinedEncoding.m_winAnsiEncoding.names[154] = "scaron";
    PredefinedEncoding.m_winAnsiEncoding.names[155] = "guilsinglright";
    PredefinedEncoding.m_winAnsiEncoding.names[156] = "oe";
    PredefinedEncoding.m_winAnsiEncoding.names[158] = "zcaron";
    PredefinedEncoding.m_winAnsiEncoding.names[159] = "Ydieresis";
    PredefinedEncoding.m_winAnsiEncoding.names[161] = "exclamdown";
    PredefinedEncoding.m_winAnsiEncoding.names[162] = "cent";
    PredefinedEncoding.m_winAnsiEncoding.names[163] = "sterling";
    PredefinedEncoding.m_winAnsiEncoding.names[164] = "currency";
    PredefinedEncoding.m_winAnsiEncoding.names[165] = "yen";
    PredefinedEncoding.m_winAnsiEncoding.names[166] = "brokenbar";
    PredefinedEncoding.m_winAnsiEncoding.names[167] = "section";
    PredefinedEncoding.m_winAnsiEncoding.names[168] = "dieresis";
    PredefinedEncoding.m_winAnsiEncoding.names[169] = "copyright";
    PredefinedEncoding.m_winAnsiEncoding.names[170] = "ordfeminine";
    PredefinedEncoding.m_winAnsiEncoding.names[171] = "guillemotleft";
    PredefinedEncoding.m_winAnsiEncoding.names[172] = "logicalnot";
    PredefinedEncoding.m_winAnsiEncoding.names[174] = "registered";
    PredefinedEncoding.m_winAnsiEncoding.names[175] = "macron";
    PredefinedEncoding.m_winAnsiEncoding.names[176 /*0xB0*/] = "degree";
    PredefinedEncoding.m_winAnsiEncoding.names[177] = "plusminus";
    PredefinedEncoding.m_winAnsiEncoding.names[178] = "twosuperior";
    PredefinedEncoding.m_winAnsiEncoding.names[179] = "threesuperior";
    PredefinedEncoding.m_winAnsiEncoding.names[180] = "acute";
    PredefinedEncoding.m_winAnsiEncoding.names[181] = "mu";
    PredefinedEncoding.m_winAnsiEncoding.names[182] = "paragraph";
    PredefinedEncoding.m_winAnsiEncoding.names[183] = "middot";
    PredefinedEncoding.m_winAnsiEncoding.names[184] = "cedilla";
    PredefinedEncoding.m_winAnsiEncoding.names[185] = "onesuperior";
    PredefinedEncoding.m_winAnsiEncoding.names[186] = "ordmasculine";
    PredefinedEncoding.m_winAnsiEncoding.names[187] = "guillemotright";
    PredefinedEncoding.m_winAnsiEncoding.names[188] = "onequarter";
    PredefinedEncoding.m_winAnsiEncoding.names[189] = "onehalf";
    PredefinedEncoding.m_winAnsiEncoding.names[190] = "threequarters";
    PredefinedEncoding.m_winAnsiEncoding.names[191] = "questiondown";
    PredefinedEncoding.m_winAnsiEncoding.names[192 /*0xC0*/] = "Agrave";
    PredefinedEncoding.m_winAnsiEncoding.names[193] = "Aacute";
    PredefinedEncoding.m_winAnsiEncoding.names[194] = "Acircumflex";
    PredefinedEncoding.m_winAnsiEncoding.names[195] = "Atilde";
    PredefinedEncoding.m_winAnsiEncoding.names[196] = "Adieresis";
    PredefinedEncoding.m_winAnsiEncoding.names[197] = "Aring";
    PredefinedEncoding.m_winAnsiEncoding.names[198] = "AE";
    PredefinedEncoding.m_winAnsiEncoding.names[199] = "Ccedilla";
    PredefinedEncoding.m_winAnsiEncoding.names[200] = "Egrave";
    PredefinedEncoding.m_winAnsiEncoding.names[201] = "Eacute";
    PredefinedEncoding.m_winAnsiEncoding.names[202] = "Ecircumflex";
    PredefinedEncoding.m_winAnsiEncoding.names[203] = "Edieresis";
    PredefinedEncoding.m_winAnsiEncoding.names[204] = "Igrave";
    PredefinedEncoding.m_winAnsiEncoding.names[205] = "Iacute";
    PredefinedEncoding.m_winAnsiEncoding.names[206] = "Icircumflex";
    PredefinedEncoding.m_winAnsiEncoding.names[207] = "Idieresis";
    PredefinedEncoding.m_winAnsiEncoding.names[208 /*0xD0*/] = "Eth";
    PredefinedEncoding.m_winAnsiEncoding.names[210] = "Ntilde";
    PredefinedEncoding.m_winAnsiEncoding.names[211] = "Oacute";
    PredefinedEncoding.m_winAnsiEncoding.names[212] = "Ocircumflex";
    PredefinedEncoding.m_winAnsiEncoding.names[213] = "Otilde";
    PredefinedEncoding.m_winAnsiEncoding.names[214] = "Odieresis";
    PredefinedEncoding.m_winAnsiEncoding.names[215] = "multiply";
    PredefinedEncoding.m_winAnsiEncoding.names[216] = "Oslash";
    PredefinedEncoding.m_winAnsiEncoding.names[217] = "Ugrave";
    PredefinedEncoding.m_winAnsiEncoding.names[218] = "Uacute";
    PredefinedEncoding.m_winAnsiEncoding.names[219] = "Ucircumflex";
    PredefinedEncoding.m_winAnsiEncoding.names[220] = "Udieresis";
    PredefinedEncoding.m_winAnsiEncoding.names[221] = "Yacute";
    PredefinedEncoding.m_winAnsiEncoding.names[222] = "Thorn";
    PredefinedEncoding.m_winAnsiEncoding.names[223] = "germandbls";
    PredefinedEncoding.m_winAnsiEncoding.names[224 /*0xE0*/] = "agrave";
    PredefinedEncoding.m_winAnsiEncoding.names[225] = "aacute";
    PredefinedEncoding.m_winAnsiEncoding.names[226] = "acircumflex";
    PredefinedEncoding.m_winAnsiEncoding.names[227] = "atilde";
    PredefinedEncoding.m_winAnsiEncoding.names[228] = "adieresis";
    PredefinedEncoding.m_winAnsiEncoding.names[229] = "aring";
    PredefinedEncoding.m_winAnsiEncoding.names[230] = "ae";
    PredefinedEncoding.m_winAnsiEncoding.names[231] = "ccedilla";
    PredefinedEncoding.m_winAnsiEncoding.names[232] = "egrave";
    PredefinedEncoding.m_winAnsiEncoding.names[233] = "eacute";
    PredefinedEncoding.m_winAnsiEncoding.names[234] = "ecircumflex";
    PredefinedEncoding.m_winAnsiEncoding.names[235] = "edieresis";
    PredefinedEncoding.m_winAnsiEncoding.names[236] = "igrave";
    PredefinedEncoding.m_winAnsiEncoding.names[237] = "iacute";
    PredefinedEncoding.m_winAnsiEncoding.names[238] = "icircumflex";
    PredefinedEncoding.m_winAnsiEncoding.names[239] = "idieresis";
    PredefinedEncoding.m_winAnsiEncoding.names[240 /*0xF0*/] = "eth";
    PredefinedEncoding.m_winAnsiEncoding.names[241] = "ntilde";
    PredefinedEncoding.m_winAnsiEncoding.names[242] = "ograve";
    PredefinedEncoding.m_winAnsiEncoding.names[243] = "oacute";
    PredefinedEncoding.m_winAnsiEncoding.names[244] = "ocircumflex";
    PredefinedEncoding.m_winAnsiEncoding.names[245] = "otilde";
    PredefinedEncoding.m_winAnsiEncoding.names[246] = "odieresis";
    PredefinedEncoding.m_winAnsiEncoding.names[247] = "divide";
    PredefinedEncoding.m_winAnsiEncoding.names[248] = "oslash";
    PredefinedEncoding.m_winAnsiEncoding.names[249] = "ugrave";
    PredefinedEncoding.m_winAnsiEncoding.names[250] = "uacute";
    PredefinedEncoding.m_winAnsiEncoding.names[251] = "ucircumflex";
    PredefinedEncoding.m_winAnsiEncoding.names[252] = "udieresis";
    PredefinedEncoding.m_winAnsiEncoding.names[253] = "yacute";
    PredefinedEncoding.m_winAnsiEncoding.names[254] = "thorn";
    PredefinedEncoding.m_winAnsiEncoding.names[(int) byte.MaxValue] = "ydieresis";
    PredefinedEncoding.m_winAnsiEncoding.names[32 /*0x20*/] = "space";
    PredefinedEncoding.m_winAnsiEncoding.names[33] = "exclam";
    PredefinedEncoding.m_winAnsiEncoding.names[34] = "quotedbl";
    PredefinedEncoding.m_winAnsiEncoding.names[35] = "numbersign";
    PredefinedEncoding.m_winAnsiEncoding.names[36] = "dollar";
    PredefinedEncoding.m_winAnsiEncoding.names[37] = "percent";
    PredefinedEncoding.m_winAnsiEncoding.names[38] = "ampersand";
    PredefinedEncoding.m_winAnsiEncoding.names[39] = "quotesingle";
    PredefinedEncoding.m_winAnsiEncoding.names[40] = "parenleft";
    PredefinedEncoding.m_winAnsiEncoding.names[41] = "parenright";
    PredefinedEncoding.m_winAnsiEncoding.names[42] = "asterisk";
    PredefinedEncoding.m_winAnsiEncoding.names[43] = "plus";
    PredefinedEncoding.m_winAnsiEncoding.names[44] = "comma";
    PredefinedEncoding.m_winAnsiEncoding.names[45] = "hyphen";
    PredefinedEncoding.m_winAnsiEncoding.names[46] = "period";
    PredefinedEncoding.m_winAnsiEncoding.names[47] = "slash";
    PredefinedEncoding.m_winAnsiEncoding.names[48 /*0x30*/] = "zero";
    PredefinedEncoding.m_winAnsiEncoding.names[49] = "one";
    PredefinedEncoding.m_winAnsiEncoding.names[50] = "two";
    PredefinedEncoding.m_winAnsiEncoding.names[51] = "three";
    PredefinedEncoding.m_winAnsiEncoding.names[52] = "four";
    PredefinedEncoding.m_winAnsiEncoding.names[53] = "five";
    PredefinedEncoding.m_winAnsiEncoding.names[54] = "six";
    PredefinedEncoding.m_winAnsiEncoding.names[55] = "seven";
    PredefinedEncoding.m_winAnsiEncoding.names[56] = "eight";
    PredefinedEncoding.m_winAnsiEncoding.names[57] = "nine";
    PredefinedEncoding.m_winAnsiEncoding.names[58] = "colon";
    PredefinedEncoding.m_winAnsiEncoding.names[59] = "semicolon";
    PredefinedEncoding.m_winAnsiEncoding.names[60] = "less";
    PredefinedEncoding.m_winAnsiEncoding.names[61] = "equal";
    PredefinedEncoding.m_winAnsiEncoding.names[62] = "greater";
    PredefinedEncoding.m_winAnsiEncoding.names[63 /*0x3F*/] = "question";
    PredefinedEncoding.m_winAnsiEncoding.names[64 /*0x40*/] = "at";
    PredefinedEncoding.m_winAnsiEncoding.names[65] = "A";
    PredefinedEncoding.m_winAnsiEncoding.names[66] = "B";
    PredefinedEncoding.m_winAnsiEncoding.names[67] = "C";
    PredefinedEncoding.m_winAnsiEncoding.names[68] = "D";
    PredefinedEncoding.m_winAnsiEncoding.names[69] = "E";
    PredefinedEncoding.m_winAnsiEncoding.names[70] = "F";
    PredefinedEncoding.m_winAnsiEncoding.names[71] = "G";
    PredefinedEncoding.m_winAnsiEncoding.names[72] = "H";
    PredefinedEncoding.m_winAnsiEncoding.names[73] = "I";
    PredefinedEncoding.m_winAnsiEncoding.names[74] = "J";
    PredefinedEncoding.m_winAnsiEncoding.names[75] = "K";
    PredefinedEncoding.m_winAnsiEncoding.names[76] = "L";
    PredefinedEncoding.m_winAnsiEncoding.names[77] = "M";
    PredefinedEncoding.m_winAnsiEncoding.names[78] = "N";
    PredefinedEncoding.m_winAnsiEncoding.names[79] = "O";
    PredefinedEncoding.m_winAnsiEncoding.names[80 /*0x50*/] = "P";
    PredefinedEncoding.m_winAnsiEncoding.names[81] = "Q";
    PredefinedEncoding.m_winAnsiEncoding.names[82] = "R";
    PredefinedEncoding.m_winAnsiEncoding.names[83] = "S";
    PredefinedEncoding.m_winAnsiEncoding.names[84] = "T";
    PredefinedEncoding.m_winAnsiEncoding.names[85] = "U";
    PredefinedEncoding.m_winAnsiEncoding.names[86] = "V";
    PredefinedEncoding.m_winAnsiEncoding.names[87] = "W";
    PredefinedEncoding.m_winAnsiEncoding.names[88] = "X";
    PredefinedEncoding.m_winAnsiEncoding.names[89] = "Y";
    PredefinedEncoding.m_winAnsiEncoding.names[90] = "Z";
    PredefinedEncoding.m_winAnsiEncoding.names[91] = "bracketleft";
    PredefinedEncoding.m_winAnsiEncoding.names[92] = "backslash";
    PredefinedEncoding.m_winAnsiEncoding.names[93] = "bracketright";
    PredefinedEncoding.m_winAnsiEncoding.names[94] = "asciicircum";
    PredefinedEncoding.m_winAnsiEncoding.names[95] = "underscore";
    PredefinedEncoding.m_winAnsiEncoding.names[96 /*0x60*/] = "grave";
    PredefinedEncoding.m_winAnsiEncoding.names[97] = "a";
    PredefinedEncoding.m_winAnsiEncoding.names[98] = "b";
    PredefinedEncoding.m_winAnsiEncoding.names[99] = "c";
    PredefinedEncoding.m_winAnsiEncoding.InitMapping();
  }

  private void InitMapping()
  {
    if (this.mapping != null)
      return;
    this.mapping = new Dictionary<string, byte>(this.names.Length);
    for (int index = 0; index < this.names.Length; ++index)
    {
      if (this.names[index] != null)
        this.mapping[this.names[index]] = (byte) index;
    }
  }

  public static PredefinedEncoding MacRomanEncoding
  {
    get => PredefinedEncoding.m_macRomanEncoding;
    private set => PredefinedEncoding.m_macRomanEncoding = value;
  }

  public string Name
  {
    get => this.m_name;
    private set => this.m_name = value;
  }

  public static PredefinedEncoding PdfDocEncoding
  {
    get => PredefinedEncoding.m_pdfdocEncoding;
    private set => PredefinedEncoding.m_pdfdocEncoding = value;
  }

  public static PredefinedEncoding StandardEncoding
  {
    get => PredefinedEncoding.m_standardEncoding;
    private set => PredefinedEncoding.m_standardEncoding = value;
  }

  public static PredefinedEncoding StandardMacRomanEncoding
  {
    get => PredefinedEncoding.m_standardMacRomanEncoding;
    private set => PredefinedEncoding.m_standardMacRomanEncoding = value;
  }

  public static PredefinedEncoding WinAnsiEncoding
  {
    get => PredefinedEncoding.m_winAnsiEncoding;
    private set => PredefinedEncoding.m_winAnsiEncoding = value;
  }
}
